travis:
  secure:
    BINSTAR_TOKEN: PV1w2tzn1XBb+yVaLwatk5HCwAKurOkEOMqnEFhlvBloq4U9tn1pxKEQnFH8j87jHLa7yv6rL7qHXLb/oeprnpgd9U7hDpvUAzXcFGrv/2Ye1NmX48Dhcny1LZEjS6qRMHPecGweneM4aw7jkCPgSQ2noQzOf3fNLH++VfMjrcfoLQeVV3O0h0kmh9PbUnq6F3u5DuIt2k+tb6pO/nvuUiqbT52LdgCkSKfa2V4v/+Z2rw2hsymETUa/pOO+0Ma3GVCXd3tXYKE08wruR71QCrtUrRycBWBln8NFqHCTR3Qq56819e37SgEhBXabTq2jGc6VHs3uWe980G7o56clEvPB3qZnrmmoZ5lmT89XaHBl829sHA0qq9mZ+JUE5eI9jo5sChmaml3mGwaTJsdGZYYXCCxxS2wFL5M8OCV5ohIKMxIRH5Eqibe+EEdp5VY+HV5zKW5bwrhVrJoY45+lUV3Q38bh8+3lLURCpzu7C1hkumyQmg2krDi9A9w/89pwpOLh7j1m6q96/3EQoeR4PHgF6qzjf9aWXwljoZ6VA/UDccyC1hqWk5cZ8cHk9eIBD7JmVbITrtdigv/dGWytB03Jq2lFpz9O4UNl+tIi4yhlAe/2Xsn1LOCGlgzpDzAN3jS3BZMufBqAjTitfx7AVgcp3exeGkz4BTxCQvwv4Dk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
